#VESSEL FLIGHT
INITIAL_PTCH=90
INITIAL_HEADING=90
INITIAL_THROTTLE=1

#ENGINE DATA
ISP=0
F_THRUST=0
FUEL_CONSUMPTION_RATE=0

#CELESTIAL BODY DATA
KERBIN_GRAVITATIONAL_PARAMETER=0

#SIMULATION 
SIMULATION_SLEEP=1


#TELEMETRY
TELEMETRY_REFRESH=0.1
FUEL_DEPLETED_THRESHOLD=0

#PHYSICS_SIMULATION
SIMULATION_POSITION_VECTOR_STEP=10
SIMULATION_TRUE_ANOMALY_STEP = 5 #degrees

#TARGET ORBIT 
TARGET_APOAPSIS=80  #KM
TARGET_PERIAPSIS=80 #KM